### ISSUE TITLE
Add D pad Joystick emulation

### ISSUE THREAD

**Issue by morecoffee1** [MiSTer-devel/CoCo3_MiSTer#1]
Add Joystick emulation for the D-Pad as you have time similar to coco2.

**Comment by alanswx** [comment]
Please test this, it should work.

**Comment by alanswx** [comment]
on the unstable nightly

**Comment by shodge12** [comment]
Now release 20211229.  Can you verify its fixed?

**Comment by morecoffee1** [comment]
Confirming D-Pad emulation bid joystick works on v211229.  Thanks
