### ISSUE TITLE
Demon Attach and castle guard

### ISSUE THREAD

**Issue by morecoffee1** [MiSTer-devel/CoCo3_MiSTer#3]
Demon Attack (1984)(Tandy)[26-3099].ccc is in black and white.  Looks like it is missing the other color signals from both component and Hdmi.  Sound also missing.  When firing I hear a static pop sound where it should be a tone.  Works fine on Coco2 core.  Found YouTube video of game playing on Coco3 so I assume it is compatible.

Was using the core version available on regular update script.

Castle guard has the same types of black and white issues.  Audio seems better.  Maybe white noise is working but not other waves.  Also color appear when castle takes a hit during flash but goes back to white and black.

**Comment by shodge12** [comment]
Hi,

Under Video Settings, turn on Artifacts.  This will enable simulated color on most of these games which are appearing BW.  It sort of works on Demon Attack, but like you I do not get sound.  I'll leave this open as the sound is a problem...

-Stan

**Comment by morecoffee1** [comment]
Thanks.  I hadn't noticed that setting until it was pointed out to me.  

I can't remember if it happened previously, today I noticed  that in demon attach the border around remind the game is white.  It is black on the Coco2 core.  Because the Easter egg is white and flashes when loading a cartridge I wonder if that is causing it.

**Comment by shodge12** [comment]
The lack of border was a problem with previous versions.  It is corrected now.

The Easter egg is used to ensure a cold start in this core.  So whenever you see it for a fraction of a second, it is the core going a cold boot.

I suggest verification through actual hardware or VCC emulator to see if the border behavior is the same...

-Stan
